version: '3.8'

services:
  email_service:
    build:
      context: ./apps/email
      dockerfile: Dockerfile
    container_name: csapp_email_stage
    ports:
      - "127.0.0.1:9091:9090"
    env_file:
      - .env
    volumes:
      - ./secrets:/run/secrets:ro,z
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: csapp_api_stage
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - .env
    environment:
      # O backend enxerga o email service via rede docker (usando o hostname do container)
      EMAIL_API_URL: http://email_service:9090
    volumes:
      - ./secrets:/run/secrets:ro,z
    restart: unless-stopped

# A rede é criada por padrão pelo compose. O MySQL está no HOST. O Backend conectará no mysql pelo IP da gateway local ou network do podman.
